import {
  AcademicCapIcon,
  BanknotesIcon,
  BoltIcon,
  BuildingLibraryIcon,
  CakeIcon,
  FaceSmileIcon,
  FilmIcon,
  GiftIcon,
  HeartIcon,
  HomeIcon,
  PaperAirplaneIcon,
  ShoppingBagIcon,
  SparklesIcon,
  TagIcon,
  TruckIcon,
  UsersIcon,
} from '@heroicons/react/24/solid';
import type { CategoryOption } from './types';

export const EXPENSE_CATEGORIES: CategoryOption[] = [
  { value: 'Food & Dining', label: 'Food & Dining', Icon: CakeIcon },
  { value: 'Transport', label: 'Transport', Icon: TruckIcon },
  { value: 'Housing', label: 'Housing', Icon: HomeIcon },
  { value: 'Utilities', label: 'Utilities', Icon: BoltIcon },
  { value: 'Health & Medical', label: 'Health & Medical', Icon: HeartIcon },
  { value: 'Entertainment', label: 'Entertainment', Icon: FilmIcon },
  { value: 'Shopping', label: 'Shopping', Icon: ShoppingBagIcon },
  { value: 'Education', label: 'Education', Icon: AcademicCapIcon },
  { value: 'Personal Care', label: 'Personal Care', Icon: SparklesIcon },
  { value: 'Travel', label: 'Travel', Icon: PaperAirplaneIcon },
  { value: 'Finance', label: 'Finance', Icon: BanknotesIcon },
  { value: 'Savings & Investments', label: 'Savings & Investments', Icon: BuildingLibraryIcon },
  { value: 'Gifts & Donations', label: 'Gifts & Donations', Icon: GiftIcon },
  { value: 'Kids & Family', label: 'Kids & Family', Icon: UsersIcon },
  { value: 'Pets', label: 'Pets', Icon: FaceSmileIcon },
  { value: 'Other', label: 'Other', Icon: TagIcon },
];
